### ISSUE TITLE
Airbrake Gem Attempts to Connect to Database in Databaseless App in Rails 6

### ISSUE THREAD

**Issue by mzagaja** [airbrake/airbrake#1222]
I am currently in the process of updating one of our applications to Rails 6 and in doing so have discovered that the AirBrake gem is somehow requiring ActiveRecord to try and connect to a database, even though this application does not use ActiveRecord to do that. This behavior does not exist in Rails 5.2. I am on version 13 of the gem. I only observe this in staging and production environments with unicorn. I can reproduce this locally with:

`RAILS_ENV=staging bundle exec unicorn -p 3000`

The backtrace on start is:

```
E, [2022-05-10T11:50:45.235854 #51441] ERROR -- : reaped #<Process::Status: pid 51443 exit 1> worker=0
I, [2022-05-10T11:50:45.236177 #51441]  INFO -- : worker=0 spawning...
I, [2022-05-10T11:50:45.238017 #51454]  INFO -- : worker=0 spawned pid=51454
I, [2022-05-10T11:50:45.238623 #51454]  INFO -- : Refreshing Gem list
Symfony User is deprecated!  Switch to Identity::User.
E, [2022-05-10T11:50:49.970388 #51454] ERROR -- : ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activerecord-6.1.5.1/lib/active_record/connection_handling.rb:323:in `connection_pool'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activerecord-6.1.5.1/lib/active_record/connection_handling.rb:319:in `connection_db_config'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/airbrake-13.0.0/lib/airbrake/rails/railtie.rb:114:in `block (2 levels) in <class:Railtie>'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activerecord-6.1.5.1/lib/active_record/base.rb:315:in `<module:ActiveRecord>'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activerecord-6.1.5.1/lib/active_record/base.rb:15:in `<top (required)>'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/coyote-0.20.1/app/models/coyote/sync_tracking.rb:10:in `<module:Coyote>'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/coyote-0.20.1/app/models/coyote/sync_tracking.rb:6:in `<top (required)>'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:424:in `block in require_or_load'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:39:in `block in load_interlock'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:39:in `load_interlock'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:402:in `require_or_load'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:375:in `depend_on'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:288:in `require_dependency'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/engine.rb:493:in `block (2 levels) in eager_load!'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/engine.rb:492:in `each'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/engine.rb:492:in `block in eager_load!'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/engine.rb:489:in `each'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/engine.rb:489:in `eager_load!'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/engine.rb:358:in `eager_load!'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/application/finisher.rb:134:in `each'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/application/finisher.rb:134:in `block in <module:Finisher>'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/initializable.rb:32:in `instance_exec'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/initializable.rb:32:in `run'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/mzagaja/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
/Users/mzagaja/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/Users/mzagaja/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
/Users/mzagaja/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
/Users/mzagaja/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:347:in `each'
/Users/mzagaja/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:347:in `call'
/Users/mzagaja/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
/Users/mzagaja/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
/Users/mzagaja/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/initializable.rb:60:in `run_initializers'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/railties-6.1.5.1/lib/rails/application.rb:391:in `initialize!'
/Users/mzagaja/Developer/roadrunner/config/environment.rb:5:in `<top (required)>'
[config.ru:21](http://config.ru:21/):in `require'
[config.ru:21](http://config.ru:21/):in `block in <main>'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
[config.ru](http://config.ru/):1:in `new'
[config.ru](http://config.ru/):1:in `<main>'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/unicorn-6.1.0/lib/unicorn.rb:54:in `eval'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/unicorn-6.1.0/lib/unicorn.rb:54:in `block in builder'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:821:in `build_app!'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:689:in `init_worker_process'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:721:in `worker_loop'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:547:in `spawn_missing_workers'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:561:in `maintain_worker_count'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:294:in `join'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/gems/unicorn-6.1.0/bin/unicorn:128:in `<top (required)>'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/bin/unicorn:23:in `load'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/bin/unicorn:23:in `<main>'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/bin/ruby_executable_hooks:22:in `eval'
/Users/mzagaja/.rvm/gems/ruby-2.7.6@roadrunner/bin/ruby_executable_hooks:22:in `<main>’
```

This error does not reproduce if I remove the Airbrake gem from the Gemfile. Let me know if there is any other information I can provide. This issue is blocking our ability to update the app to Rails 6, so besides an expedient fix, if there is a temporary workaround you can suggest, it’d be appreciated.

**Comment by kyrylo** [comment]
Hi, @mzagaja!

[When Active Record is detected](https://github.com/airbrake/airbrake/blob/827a760e20ee40e56763b6661bdabe320d221df9/lib/airbrake/rails/railtie.rb#L101), we hook into it and define our custom code. The Airbrake gem doesn't try to require Active Record anywhere. How come you have Active Record defined if you don't use it anywhere?

Perhaps you can see this error on Rails 6 because something was changed in Rails 6.1 and `ActiveRecord::Base.connection_db_config` establishes a connection now. I do wonder why it wasn't an error on pre-6.1 Rails (even with a different call that we used).

Could you please give https://github.com/airbrake/airbrake/pull/1224 a run? I would appreciate it if you could run this PR against Rails 5.2 as well.

**Comment by mzagaja** [comment]
Thanks so much for working on this. I don't specifically attempt to load ActiveRecord in my app (I've pulled it out as deep as I can go) but think one of the gems might try to do this. It's a bit odd that it needs/uses it without a configuration.

```ruby
[45, 54] in ~/.rvm/gems/ruby-2.7.5@roadrunner/bundler/gems/airbrake-dfa9564fb3a0/lib/airbrake/rails/railties/active_record_tie.rb
    45|           # Filter out parameters from SQL body.
    46|           #
    47|           # Rails 6+ introduces the `configs_for` API instead of the deprecated
    48|           # `#[]`, so we need an updated call.
    49|           configurations = ::ActiveRecord::Base.configurations
=>  50|           debugger
    51|           adapter =
    52|             if configurations.respond_to?(:configs_for)
    53|               cfg = configurations.configs_for(env_name: ::Rails.env).first
    54|               # Rails 7+ API : Rails 6 API.
=>#0	Airbrake::Rails::Railties::ActiveRecordTie#tie_activerecord_apm at ~/.rvm/gems/ruby-2.7.5@roadrunner/bundler/gems/airbrake-dfa9564fb3a0/lib/airbrake/rails/railties/active_record_tie.rb:50
  #1	block in call at ~/.rvm/gems/ruby-2.7.5@roadrunner/bundler/gems/airbrake-dfa9564fb3a0/lib/airbrake/rails/railties/active_record_tie.rb:21
  # and 66 frames (use `bt' command for all frames)
(rdbg) configurations
#<ActiveRecord::DatabaseConfigurations:0x00007faf08961590 @configurations=[]>
(ruby) configurations.respond_to?(:configs_for)
true
(ruby) configurations.configs_for(env_name: ::Rails.env).first
nil
(ruby) cfg = configurations.configs_for(env_name: ::Rails.env).first
nil
(ruby) cfg.respond_to?(:adapter) ? cfg.adapter : cfg.config['adapter']
eval error: undefined method `config' for nil:NilClass
  (rdbg)//Users/mzagaja/.rvm/gems/ruby-2.7.5@roadrunner/bundler/gems/airbrake-dfa9564fb3a0/lib/airbrake/rails/railties/active_record_tie.rb:1:in `tie_activerecord_apm'
nil
(ruby) configurations.respond_to?(:configs_for)
true
(ruby) configurations.present?
false
(ruby) configurations.blank?
true
```

I found the following solution seems to work:

```ruby
        def tie_activerecord_apm
          return unless defined?(ActiveRecord) && ::ActiveRecord::Base.configurations.present?

          # Send SQL queries.
          ActiveSupport::Notifications.subscribe(
            'sql.active_record',
            @active_record_subscriber,
          )

          # Filter out parameters from SQL body.
          #
          # Rails 6+ introduces the `configs_for` API instead of the deprecated
          # `#[]`, so we need an updated call.
          configurations = ::ActiveRecord::Base.configurations
          adapter =
            if configurations.respond_to?(:configs_for)
              cfg = configurations.configs_for(env_name: ::Rails.env).first
              # Rails 7+ API : Rails 6 API.
              cfg.respond_to?(:adapter) ? cfg.adapter : cfg.config['adapter']
            else
              configurations[::Rails.env]['adapter']
            end

          Airbrake.add_performance_filter(Airbrake::Filters::SqlFilter.new(adapter))
        end
```

This fix also seems to work on Ruby 2.6.9 and Rails 5.2.7. Let me know if this makes sense or if there are other things you want me to try. Thanks again for your help!

**Comment by kyrylo** [comment]
Thanks for digging into this issue and helping me debug it. This information is enough to move forward. When you wake up, the new version of the gem with this fix has already been released.

**Comment by mzagaja** [comment]
Thanks so much!! I will fully confirm on our deployment Monday but testing locally the fix is looking good here.
